### ISSUE TITLE
Unable to configure certificates for a root domain

### ISSUE THREAD

**Issue by RichMercer** [n3wt0n/AzureWebAppSSLManager#14] opened 2019-12-03 11:35 UTC
It's not currently possible to configure a certificate for a root domain. The error "root hostname cannot be assigned with a CName record" is returned. This is due to the way domains are split in AzureHelper.cs:210. e.g. for the domain 'google.com' the domain will be set as "com" and the subdomain as "google". It works correctly for "www.google.com" though as it's correctly parsed.

**Comment by RichMercer** [comment] 2019-12-03 12:37
I've also found the same issue exists for wildcard domains on the root domain e.g. *.google.com.

**Comment by n3wt0n** [comment] 2019-12-03 12:50
mmmh, strange... I've used it for a root domain before, I will try again when I have a bit of free time

**Comment by n3wt0n** [comment] 2019-12-03 19:41
For the Root Domain you're right, there is a problem on the way it's split.

But for wildcards domains there isn't, because it's not going to parse it "as is" but instead is apllying to the list of actual hostnames that are part of the WebApp/FunctionApp configuration.

That said, the error you are getting "root hostname cannot be assigned with a CName record" is not because the way it's split, but it is a limitation on Azure DNS. You cannot create a CName for a root hostname.

I will add this to the documentation as a limitation

**Comment by RichMercer** [comment] 2019-12-04 10:20
So I've tracked the issue with root domain certs down to this line: https://github.com/n3wt0n/AzureWebAppSSLManager/blob/50fdaf2ce554e770e937d31756a528d0e0b88bbb/src/WebAppSSLManager/AzureHelper.cs#L264

Is there a reason the line is needed as without it things work perfectly. 

Also, commenting out lines 179-181, along with the fix above, solves my issue with wildcard certs as it was previously trying install a wildcard cert to the root domain resulting in a mismatch. It should be installing the wildcard cert to the wildcard custom domain entry. I can create a PR for this if you like.

**Comment by n3wt0n** [comment] 2019-12-04 14:24
The "WithThirdPartyHostnameBinding" function is needed for domains that are not purchased via Azure. Info [Here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.appservice.fluent.webappbase.definition.iwithhostnamebinding-1.withthirdpartyhostnamebinding?view=azure-dotnet)

If you use a domain which has been purchased on the Azure portal that would work without that line. I've included it because in 99% of the cases I've seen people uses external domains rather than Azure-purchased ones.

about lines 179-181, I'd need to do more investigation about it. But that imho would work only if you define a hostname bidning called "*.yourdomain.xx", which is not normally what I've seen done (tbh I didn't think it's possible", while if you call it "yourdomain.xx" that won't work.

**Comment by n3wt0n** [comment] 2019-12-04 14:25
Do you think it would make sense making a fix for allowing the user to specify if it's an externally purchased domain or an Azure purchased domain?

**Comment by RichMercer** [comment] 2019-12-04 14:26
To the first point, I've tested it today with a domain purchased from GoDaddy and it worked fine without that call.

For the wildcard issue, AFAIK you have to add the wildcard domain otherwise it will not let you assign the certificate due to a mismatch between the domain and cert domain.

**Comment by n3wt0n** [comment] 2019-12-04 14:31
> To the first point, I've tested it today with a domain purchased from GoDaddy and it worked fine without that call.

That's interesting... When I first developed that bit I ran into an exception (several times) and the only way to fix it was adding that line. Checking the docs (at that time) confirmed I had to do that. I wonder if the App Service team changed something in the meantime...

> For the wildcard issue, AFAIK you have to add the wildcard domain otherwise it will not let you assign the certificate due to a mismatch between the domain and cert domain. That is to say that Azure won't let you add a custom domain called [www.yourdomain.com](http://www.yourdomain.com) and assign the cert *.yourdomain.com to it.

Gotcha. I think the main thing here is that, if you look at the code, what I do for wildcards is:

1. Generate the wildcard certificate for *.domain.com
2. Get all the hostname bindings for that app service (let's call it aaa.domain.com and bbb.domaind.com)
3. Assign the wildcard certificate to the individual hostname bindings. That works well in my production environment for example.

I do it this way because anyway for App Service to work you have to specify the individual hostname bindings anyway (Am I wrong)?

**Comment by RichMercer** [comment] 2019-12-04 14:37
So I tried that today and when it tried to assign the *.yourdomain.com certificate to the www.yourdomain.com custom domain it threw an error (something like a host mismatch). That is the same experience as trying to do it via the portal. If you try and add a binding for www it will not even show you the wildcard cert in the dropdown to select from.

I would say if you have created specific host bindings, each should try and get its own cert for that host name. The wildcard cert is useful when you've added a wildcard host domain. In my case it's for a multi tenant application so I don't know what the hostnames will be, hence using a wildcard mapping. Hopefully that makes sense?

**Comment by n3wt0n** [comment] 2019-12-04 15:34
I think something weird is going on here :)

I can actually do that:

![image](https://user-images.githubusercontent.com/13121206/70156040-4d32f980-1681-11ea-9ad2-c2bddbb21549.png)

The cert is a wildcard one, and I assign it to specific subdomains.
This is for a multitenant app as well.

I'm doing this way because AFAIK it is (was?) not possible to assign to App Service a wildcard domain for it to handle, but you need to specify every single subdmain. (I do that calling the App Service APIs doing provisioning of a new tenant)

**Comment by RichMercer** [comment] 2019-12-04 15:42
Ok, you're right, I was trying to add it to the root domain and of course, that's not valid. However, I can add the wildcard cert to the www host, so that works. I'll test that again using the function to see what happens. I think it wasn't added it to the wildcard custom domain, which it needs to be really. I'll do that later when I have time.

The good news though is you should be able to add the wildcard domain and not have to add tenants individually. Let me know if you have any issues as it should be possible and it's one less thing to go wrong. 👍🏼

**Comment by RichMercer** [comment] 2019-12-05 10:30
I tested this today and for wildcard certs, I've added the code back in to my fork. It does correctly add the wildcard cert to all subdomains, including the wildcard hostname. 

I've left out the .WithThirdPartyHostnameBinding(domain, subdomain) though for now and I'll create a PR. You can test it with your domain if you wish. 👍🏼

**Closed** 2019-12-23 01:33 UTC
Labels: enhancement
