### ISSUE TITLE
Deployment on Azure fails

### ISSUE THREAD

**Issue by robert-schmidt-motesque** [n3wt0n/AzureWebAppSSLManager#38] opened 2021-05-15 13:33 UTC
Hey Davide,

I'm trying to deploy the app to Azure through the provided template. 

I've created the Service Principal, SendGrid etc and created also a new Ressource Group.

I've assigned to all parameters the corresponding values

The deployment of the webapp leads to a failure with reason "Conflict"
![image](https://user-images.githubusercontent.com/50239928/118363036-c9c64900-b592-11eb-98f4-8da17846e5a8.png)

Any idea what could be the reason?

Best regards,
Robert

**Comment by rfreytag** [comment] 2021-05-15 15:10
I had the same problem.  I think it was a type conflict.  But I think I uncovered a few other problems.  

Eventually I stopped using the GitHub install button.  No matter how I edited the *.template.*.json and *.parameters.*.json files I could not get meaningful results.  

I installed through the Azure CLI which returned useful messages.

These are the errors I am fixing and will push up when done:

- Two template values are 'string' when they should be "int" and the accompanying numbers ( 0 and 30), needed to NOT be surrounded by quotes (").  That took care of the conflict.  

- The Azure CLI reports that the *.parameters.*.json file should only have values and no type-s.  

I manually deployed the Azure function to the cloud.

- Don't forget to put the needed information in the blog storage so the Azure function knows what to do.  

Hope this helps,
Richard F. 




-----Original Message-----
From: "Robert Schmidt" ***@***.***>
Sent: Saturday, May 15, 2021 9:33am
To: "n3wt0n/AzureWebAppSSLManager" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [n3wt0n/AzureWebAppSSLManager] Deployment on Azure fails (#38)

Hey Team,

I'm trying to deploy the app to Azure through the provided template. 

I've created the Service Principal, SendGrid etc and created also a new Ressource Group.

I've assigned to all

The deployment of the webapp leads to a failure with reason "Conflict"
![image](https://user-images.githubusercontent.com/50239928/118363036-c9c64900-b592-11eb-98f4-8da17846e5a8.png)

Any idea what could be the reason?

Best regards,
Robert



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/n3wt0n/AzureWebAppSSLManager/issues/38

**Comment by rfreytag** [comment] 2021-05-15 15:17
I had the same problem.  I think it was a type conflict.  But I think I uncovered a few other problems.  

Eventually I stopped using the GitHub install button.  No matter how I edited the *.template.*.json and *.parameters.*.json files I could not get meaningful results.  

I installed through the Azure CLI which returned useful messages.

These are the errors I am fixing and will push up when done:

- Two template values are 'string' when they should be "int" and the accompanying numbers ( 0 and 30), needed to NOT be surrounded by quotes (").  That took care of the conflict.  

- The Azure CLI reports that the *.parameters.*.json file should only have values and no type-s.  

I manually deployed the Azure function to the cloud.

- Don't forget to put the needed information in the blog storage so the Azure function knows what to do.  

Hope this helps,
Richard F. 




-----Original Message-----
From: "Robert Schmidt" ***@***.***>
Sent: Saturday, May 15, 2021 9:33am
To: "n3wt0n/AzureWebAppSSLManager" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [n3wt0n/AzureWebAppSSLManager] Deployment on Azure fails (#38)

Hey Team,

I'm trying to deploy the app to Azure through the provided template. 

I've created the Service Principal, SendGrid etc and created also a new Ressource Group.

I've assigned to all

The deployment of the webapp leads to a failure with reason "Conflict"
![image](https://user-images.githubusercontent.com/50239928/118363036-c9c64900-b592-11eb-98f4-8da17846e5a8.png)

Any idea what could be the reason?

Best regards,
Robert



-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/n3wt0n/AzureWebAppSSLManager/issues/38

**Comment by n3wt0n** [comment] 2021-05-24 07:29
Hey @robert-schmidt-motesque sorry for the late reply, I've taken a week off :). I will look into this. and let you know

**Closed** 2021-05-24 08:16 UTC
Labels: question

**Comment by n3wt0n** [comment] 2021-05-24 08:45
@robert-schmidt-motesque I've fixed this.

The issue @rfreytag reported, of the Int parameters being specified as String was a non-issue, or better it was a param mismatch but that didn't cause the problem (I've fixed it anyway)

The problem was caused by the fact that I've changed the branch from `master` to `main` but I've forgotten to change the pointer in the ARM Template, hence the deployment was still looking for pulling the code from the master branch.

Now that is solved
